### PR TITLE
[BUGFIX] add workaround for Win/Nvidia mouse coordinates

### LINKED ISSUE #46: Labels on map not clickable // Nvidia QGLWidget mouse coordinates
I am used to have quick access on detailed information about a flight or an airport when I click on the callsign or four-letter code. But this doesn't work on the latest release of Qutescoop

### PR DESCRIPTION
**Pull request by jonaseberle**
This is a work around. While the MouseEvent seems to
arbitrarily contain wrong coordinates in `pos()` on some Nvidia drivers
under some circumstances (confirmed in driver versions 496.49 and 511.65),
using the widget's `mapFromGlobal(QCursor::pos())` seems to not carry
the error and be transparent when the error does not surface at all.

Resolves: qutescoop/qutescoop#46

### CODE REVIEW

**Comment by jonaseberle** [comment]
@twSimulations @dsamuelis @droesen it would be great if you could test this. 
The test build can be found under "Checks" on top, then "Artifacts"

**Comment by twSimulations** [comment]
No issues on my side. So everything seems to be fine to me

**Comment by droesen** [comment]
On first glance, seems to be fine here too. But I wasn't reliably getting the problem anyway, so I have to check over the week...

**Comment by dsamuelis** [comment]
Yes the present version works fine for me, thanks much! 

Sample log line of the present release:
2022-03-08T19:35:29.601Z [DBG] GLWidget::mouseReleaseEvent left btn before objectsAt() "widget[width=1720, height=959], event[x=1071, y=322], mapFromGlobal(used value)[x=1063, y=291], global[x=1263,y=335] onGlobe=1, globe[lat=53.5991, lon=14.8843]"

**Comment by jonaseberle** [comment]
> Sample log line of the present release: ...
`event[x=1071, y=322], mapFromGlobal(used value)[x=1063, y=291],...`

Nice, that was when the problem would have been present without the workaround.

Let's get that in.

**Pull request merged**
