### PR TITLE
Update firdisplay.dat

### PR DESCRIPTION
**Pull request by diibify**
26 NOV 2021

- added new EUC VACC Maastricht sectors EURM_E and EURM_W
- corrected a wrong coordinate in sector LSAS
- corrected a wrong coordinate in sector LON_N
- added South America FSS station names with "dashes" and "underscores" to cover both cases. VatSpy has it with "dashes", but the real ATC login seems to be with an "underscore", e.g. SAM-E_FSS vs. SAM_E_FSS

### CODE REVIEW

**Comment by jonaseberle** [comment]
Thanks and greetz to flyingfox ;)

I'll just merge.

Btw I just installed XPlane 11 yesterday. I might have a comeback ;)

**Comment by jonaseberle** [comment]
Shouldn't we also update https://github.com/qutescoop/qutescoop/blob/master/data/dataversions.txt ?
I guess that's still required for clients to download the updated files.

**Comment by diibify** [comment]
Nice to hear that - I look forward to hearing you online again soon.

Good point with dataversions.txt. To be honest, I don't know anything about it. Can you give me some hint or change it yourself?

**Comment by jonaseberle** [comment]
I changed it.
Basically QuteScoop loads https://raw.githubusercontent.com/qutescoop/qutescoop/master/data/dataversions.txt and compares the versions there with the files it has downloaded already. Then, if something is newer online, it will be pulled.

**Comment by diibify** [comment]
I didn't even think about it. I deactivated it because it still wanted to access http://svn.code.sf.net/p/qutescoop/code/trunk/data/dataversions.txt

**Comment by jonaseberle** [comment]
Hmm, we changed the URL in the code last year. 

I am on Linux and am able to use the newer versions.
If you are on the old release from 2013 the online update won't work and you'd have to manually put the files in their locations.

**Comment by diibify** [comment]
I am on 2.1.13.1beta The latest version v2.2-alpha.1 (for Windows) ist not working cause of missing .dlls and so on.

**Pull request merged**
