### PR TITLE
Update airports.dat

### PR DESCRIPTION
**Pull request by diibify**
Added:
LIMM: LIMM_APP (Milano Radar)
ESSEX: ESSEX_APP (EGSS EGGW EGSC)

Credits @FlyingFoxVATSIM

### CODE REVIEW

**Comment by jonaseberle** [comment]
Thanks. 
image
We need to clean that a bit. Probably the line endings have been changed. They should be the same as the original file.

**Comment by diibify** [comment]
Even a simple edit without change results in 36,571 additions and 36,571 deletions. It may be that the problem is once again in front of the PC. Maybe you could add the two lines?
`LIMM:Milano APP LIMC LIML LIME:Milan:Italy:45.5:9`
`ESSEX:Stansted Radar EGSS EGGW EGSC:London:United Kingdom:51.88499832:0.235`

**Comment by jonaseberle** [comment]
No problem. I'll take care.

**Comment by FlyingFoxVATSIM** [comment]
> No problem. I'll take care.
Can we permanently add "artificial airports" like the ones above? Or will it be a manual intervention each team a new AIRAC gets processed? We may have a few more of those "artificial airports" that need to be added, e.g. "SY" to properly show "SY_APP" (YSSY), "ML" for "ML_APP" (YMML), RIO_APP for Rio de Janeiro etc..

May it be worth introducing a separate file with those artificial airports only?

**Comment by jonaseberle** [comment]
Ok, I changed line endings back and now we can see what actually changed (https://github.com/qutescoop/qutescoop/pull/181/files). The line endings had been changed to Windows (CRLF).

I get the intention now: This shall show approach controllers that don't have a login prefix that is an airport ICAO code.

With this workaround they'll show up as a "pseudo"-airport with the "APP"-circle but they won't show up in the ATC lists of the airports they cover (which I also find quite important).

Note:  LIMM_APP routinely covers LSZA, too as I found out lately so Ive added it.

> May it be worth introducing a separate file with those artificial airports only? 

Yes, I think we should add a new file that allows to map a controller login prefix to 1 or multiple airports. 
I've added a task to do this "properly" in https://github.com/qutescoop/qutescoop/issues/182 as a "letter of intent" :)

**Comment by jonaseberle** [comment]
It is live and looks good:
image

**Pull request merged**
