### PR TITLE
[TASK] remove big textures (user feedback needed)

### PR DESCRIPTION
**Pull request by jonaseberle**
We are shipping these textures currently

```
total 82M
 40K 1024px-continents.png
 84K 1024px-toposhaded.png
372K 1440px-elevation.png
396K 2048px-color.png
500K 2048px-contrast.png
352K 2048px-lights.png
288K 2048px-toposhaded.png
1,2M 2048px.png
1,3M 4096px-color.png
2,1M 4096px.png
 17M 8192px-arctic-toposhaded.png
 14M 8192px-topo.png
1,5M 10800px-continents.png
 16M 10800px-lights.png
 29M 10800px.png
```

I never had success with textures bigger than 4096px.
Have you used 8192px or above successfully?

If not, let's remove them and save a lot of MB of download size.

### CODE REVIEW

**Comment by diibify** [comment]
I am using the 8192px-arctic-toposhade...

**Comment by jonaseberle** [comment]
I think it is fine to remove the 10800px textures then. 
I'll merge that tomorrow if there are no objections.

**Comment by FlyingFoxVATSIM** [comment]
I am also using the 8192px arctic toposhade. It may be worth investigating if we can get some more crisp/detailed maps. I tried the 10800px map, it worked for me, but I did not see a huge difference in quality.

**Comment by diibify** [comment]
It would be okay for me. And yes, would there be a higher resolution image source somewhere?

**Comment by twSimulations** [comment]
I am also using "8192px arctic toposhade". I don't like the look of other textures because they are too blurry for my personal taste

**Comment by jonaseberle** [comment]
Ok, so it basically works with the 10800px but there is not a huge improvement. Then I would say let's remove them.

I am very impressed what https://github.com/albar965/littlenavmap/ does, especially with https://github.com/AmbitiousPilots/LittleNavmapOFMTheme this is such a nice map. I know they use [KDE marble engine](https://marble.kde.org/) under the hood.

**Comment by twSimulations** [comment]
Speaking of LittleNavMap, I mainly use it for checking free stands at departures airports before logging-in onto VATSIM. Not sure if it is possible to have this feature in Qutescoop as well. However, it would be really great.

https://abload.de/img/unbenanntx0j4b.jpg

**Comment by jonaseberle** [comment]
> checking free stands at departures airports before logging-in onto VATSIM

LNM parses X-Plane sceneries for this which is awesome. Even if we could get the stand positions it really comes to life in LNM with all the airport layout. Just [like the VATGER info (under "Stands")](https://vatsim-germany.org/pilots/aerodrome/EDDM) would be too "minor" (I like sexy UI) for me to pursue it.

Coming back to texturing:

Both of these are not really convincing:

8192px
image
10800px
image

Anyways, I am going to remove the 10800px now to cut down on download size.

I am continuing the discussion about map graphics [in a new issue](https://github.com/qutescoop/qutescoop/issues/103) since it might else be burried in this merged pull request.

**Pull request merged**
