### PR TITLE
Switch to the new JSON bookings API

### PR DESCRIPTION
**Pull request by Luca0208**
See #171
The new booking API does not contain an option for links to be included, so that can probably be removed from the UI.
Unfortunately I don't know how the QT UI stuff works, so this needs to be done by someone else.

### CODE REVIEW

**Comment by jonaseberle** [comment]
Thanks Luca!

**Comment by jonaseberle** [comment]
I've played around with it a bit and cleaned up the dialog.

It shows the CID and (if we have one) the Alias:

image

I think it is ready. What do you think?

**Comment by Luca0208** [comment]
Looks good, thanks for the cleanup work!

**Comment by jonaseberle** [comment]
I am just doing one last rebase onto master. Sorry for the force-push.

**Pull request merged**
