### PR TITLE
[FEATURE] allow adding name aliases for friends

### LINKED ISSUE #62: Alias in the friendslist
Since it is now permitted to be online at VATSIM without a name, I wanted to suggest whether it might be possible to expand our friends list with an alias that you assign yourself, which can then be displayed in the list as an alternative. Unfortunately, some people are still only online with their ID, but I would still like to have them in the list.

Maybe you have other ideas or suggestions on how to get around the "problem".

### PR DESCRIPTION
**Pull request by jonaseberle**
Since it is now permitted to be online at VATSIM without a name, you can now add an alias for a friend that is shown in addition to the login name.

In order to add an alias, double-click an entry in the friends list.

Fixes #62

I am not sure about the usability yet - double clicking is a bit weird because single click already opens the client dialog.

image

### CODE REVIEW

**Comment by diibify** [comment]
Wow, thank you so much! 

A double click is certainly not so intuitive at first glance, as there is no such thing in QT at the moment. Maybe it's more of a right-click (by the way, a double right click already works now)? 

The format is great "Alias | VATSIM data" is super! You made my day!

**Comment by diibify** [comment]
Is it possible that something is a bit wrong with the sorting now?

Screenshot 2022-02-15 221134

**Comment by jonaseberle** [comment]
Yes, I think I accidentally dropped the sorting. I'll have a look if I can bring it back easily.

Regarding the question where to add/edit an alias:
I think here in the pilot/controller dialogs would be the most obvious place:
image

It then does not have to be a friends-alias - we can make it a more general client-alias (a VATSIM ID => alias).

**Comment by jonaseberle** [comment]
I've brought the friend list sorting back.

And what do you think about that?
image

**Comment by diibify** [comment]
I believe that this is a good solution. Maybe you could write the CID in the pop-up window again [Set an alias for xxx (1000000)]. Thanks again :)

**Comment by jonaseberle** [comment]
It shows the chosen "name". A better example would be
image

Could you test it (Downloads under "Checks" on the top) and approve if this works ok?

**Comment by diibify** [comment]
Works well. Maybe you could add a small tooltip to explain the button. And you could think about putting a space before and after the "|". It might be clearer.

**Comment by jonaseberle** [comment]
I've added the button tooltip and used " | ".
I think this will be the Highlight Feature for v2.5.0 so thank you for the idea! I reckon we could call the version "v2.5.0 Who's there?" ;)

**Comment by diibify** [comment]
I'm so in! Thank you for your commitment!

**Pull request merged**
